### ISSUE TITLE
YARA tags are not present

### ISSUE THREAD

**Issue by yassirlaaouissi** [blackmassgroup/v_exchange#8]
virus.exchange has tags, new site doesnt:

![image](https://github.com/blackmassgroup/vx_underground/assets/59022605/d76042cc-2db8-41da-939a-ec5852d07903)
![image](https://github.com/blackmassgroup/vx_underground/assets/59022605/83565d09-199e-4d2a-b827-f250bc936121)

**Comment by guessthepw** [comment]
I believe these can be pulled from Malcore.

**Comment by djnnvx** [comment]
cool, will fork & look at it over the week-end
